// Datos centrales del sitio EnglishKids: libros, categorías y vocabulario.
// "art" selecciona la ilustración SVG de portada (components/illustrations/BookCoverArt.js).
// "emoji" se usa para tarjetas pequeñas de vocabulario (flashcards, quiz, vista previa).

export const CATEGORIES = [
  { id: "todos", label: "Todos" },
  { id: "escuela", label: "Escuela" },
  { id: "familia", label: "Familia" },
  { id: "animales", label: "Animales" },
  { id: "comida", label: "Comida" },
  { id: "naturaleza", label: "Naturaleza" },
  { id: "colores", label: "Colores y formas" },
  { id: "numeros", label: "Números" },
  { id: "cuerpo", label: "Cuerpo humano" },
  { id: "lugares", label: "Lugares" },
  { id: "celebraciones", label: "Celebraciones" },
];

export const CATEGORY_COLORS = {
  escuela: "blue",
  familia: "pink",
  animales: "green",
  comida: "orange",
  naturaleza: "teal",
  colores: "purple",
  numeros: "blue",
  cuerpo: "pink",
  lugares: "teal",
  celebraciones: "orange",
};

export const TAG_CLASSES = {
  blue: "bg-brand-blue",
  pink: "bg-brand-pink",
  green: "bg-brand-green",
  orange: "bg-brand-orange",
  teal: "bg-brand-teal",
  purple: "bg-brand-purple",
};

export const COVER_GRADIENTS = {
  escuela: "from-[#d9e8ff] to-[#b7d1ff]",
  familia: "from-[#ffdde6] to-[#ffc2d1]",
  animales: "from-[#d8f5e9] to-[#b3ebd0]",
  comida: "from-[#ffe6cf] to-[#ffd1a3]",
  naturaleza: "from-[#d3f3ee] to-[#a8e6da]",
  colores: "from-[#ecdcff] to-[#d7bfff]",
  numeros: "from-[#d9e8ff] to-[#b7d1ff]",
  cuerpo: "from-[#ffdde6] to-[#ffc2d1]",
  lugares: "from-[#d3f3ee] to-[#a8e6da]",
  celebraciones: "from-[#ffe6cf] to-[#ffd1a3]",
};

export const BOOKS = [
  {
    id: "my-world-in-english",
    title: "My World in English",
    category: "escuela",
    unit: "Unidad 1 - 6",
    art: "world",
    topics: ["Saludos", "Presentaciones"],
    grade: "3° de primaria",
    pages: 68,
    format: "Digital (PDF interactivo)",
    idioma: "Inglés - Español",
    description:
      "Un libro lleno de historias y actividades para que los niños practiquen inglés en situaciones de la vida real. Ideal para 3° de primaria.",
    learn: [
      "Saludos y presentaciones",
      "Vocabulario básico",
      "Conversaciones sencillas",
      "Actividades interactivas",
      "Ilustraciones a todo color",
    ],
    vocab: [
      { word: "Hello", emoji: "👋" },
      { word: "Hi", emoji: "🙋" },
      { word: "Good morning", emoji: "🌅" },
      { word: "Good afternoon", emoji: "🌤️" },
      { word: "Good night", emoji: "🌙" },
      { word: "Bye", emoji: "👋" },
      { word: "See you", emoji: "😊" },
    ],
  },
  {
    id: "animals-around-us",
    title: "Animals Around Us",
    category: "animales",
    unit: "Unidad 1 - 6",
    art: "animals",
    topics: ["Animales", "Naturaleza"],
    grade: "3° de primaria",
    pages: 64,
    format: "Digital (PDF interactivo)",
    idioma: "Inglés - Español",
    description:
      "Descubre los animales del mundo mientras aprendes sus nombres en inglés con historias, juegos y actividades para colorear.",
    learn: [
      "Nombres de animales",
      "Sonidos y hábitats",
      "Frases descriptivas simples",
      "Juegos de memoria",
      "Ilustraciones a todo color",
    ],
    vocab: [
      { word: "Lion", emoji: "🦁" },
      { word: "Elephant", emoji: "🐘" },
      { word: "Cat", emoji: "🐱" },
      { word: "Dog", emoji: "🐶" },
      { word: "Bird", emoji: "🐦" },
      { word: "Fish", emoji: "🐟" },
      { word: "Monkey", emoji: "🐒" },
      { word: "Rabbit", emoji: "🐰" },
    ],
  },
  {
    id: "at-school",
    title: "At School",
    category: "escuela",
    unit: "Unidad 1 - 6",
    art: "school",
    topics: ["Escuela", "Objetos"],
    grade: "3° de primaria",
    pages: 60,
    format: "Digital (PDF interactivo)",
    idioma: "Inglés - Español",
    description:
      "Aprende el vocabulario del salón de clases: útiles escolares, personas y rutinas diarias en la escuela.",
    learn: [
      "Útiles escolares",
      "Personas en la escuela",
      "Rutinas y horarios",
      "Preguntas y respuestas simples",
      "Ilustraciones a todo color",
    ],
    vocab: [
      { word: "Book", emoji: "📖" },
      { word: "Pencil", emoji: "✏️" },
      { word: "Backpack", emoji: "🎒" },
      { word: "Teacher", emoji: "🧑‍🏫" },
      { word: "Classroom", emoji: "🏫" },
      { word: "Chair", emoji: "🪑" },
      { word: "Desk", emoji: "🪵" },
      { word: "Ruler", emoji: "📏" },
    ],
  },
  {
    id: "my-family",
    title: "My Family",
    category: "familia",
    unit: "Unidad 1 - 6",
    art: "family",
    topics: ["Familia", "Personas"],
    grade: "3° de primaria",
    pages: 62,
    format: "Digital (PDF interactivo)",
    idioma: "Inglés - Español",
    description:
      "Conoce el vocabulario de la familia y aprende a describir a las personas que más quieres en inglés.",
    learn: [
      "Miembros de la familia",
      "Descripciones simples",
      "Posesivos básicos (my, your)",
      "Actividades interactivas",
      "Ilustraciones a todo color",
    ],
    vocab: [
      { word: "Mother", emoji: "👩" },
      { word: "Father", emoji: "👨" },
      { word: "Sister", emoji: "👧" },
      { word: "Brother", emoji: "👦" },
      { word: "Grandmother", emoji: "👵" },
      { word: "Grandfather", emoji: "👴" },
      { word: "Baby", emoji: "👶" },
      { word: "Family", emoji: "👨‍👩‍👧‍👦" },
    ],
  },
  {
    id: "food-and-fun",
    title: "Food and Fun",
    category: "comida",
    unit: "Unidad 1 - 6",
    art: "food",
    topics: ["Comida", "Vocabulario"],
    grade: "3° de primaria",
    pages: 58,
    format: "Digital (PDF interactivo)",
    idioma: "Inglés - Español",
    description:
      "Un recorrido delicioso por el vocabulario de la comida, con actividades para practicar gustos y preferencias.",
    learn: [
      "Nombres de alimentos",
      "Gustos y preferencias (I like / I don't like)",
      "Comidas del día",
      "Juegos de vocabulario",
      "Ilustraciones a todo color",
    ],
    vocab: [
      { word: "Pizza", emoji: "🍕" },
      { word: "Apple", emoji: "🍎" },
      { word: "Milk", emoji: "🥛" },
      { word: "Bread", emoji: "🍞" },
      { word: "Juice", emoji: "🧃" },
      { word: "Cake", emoji: "🍰" },
      { word: "Rice", emoji: "🍚" },
      { word: "Egg", emoji: "🥚" },
    ],
  },
  {
    id: "nature-around-us",
    title: "Nature Around Us",
    category: "naturaleza",
    unit: "Unidad 1 - 6",
    art: "nature",
    topics: ["Naturaleza", "Plantas"],
    grade: "3° de primaria",
    pages: 60,
    format: "Digital (PDF interactivo)",
    idioma: "Inglés - Español",
    description:
      "Explora el mundo natural: plantas, clima y paisajes, mientras construyes vocabulario en inglés.",
    learn: [
      "Elementos de la naturaleza",
      "El clima",
      "Frases descriptivas",
      "Actividades al aire libre",
      "Ilustraciones a todo color",
    ],
    vocab: [
      { word: "Tree", emoji: "🌳" },
      { word: "Flower", emoji: "🌸" },
      { word: "Sun", emoji: "☀️" },
      { word: "Moon", emoji: "🌙" },
      { word: "River", emoji: "🏞️" },
      { word: "Mountain", emoji: "⛰️" },
      { word: "Cloud", emoji: "☁️" },
      { word: "Rainbow", emoji: "🌈" },
    ],
  },
  {
    id: "colors-and-shapes",
    title: "Colors and Shapes",
    category: "colores",
    unit: "Unidad 1 - 4",
    art: "colors",
    topics: ["Colores", "Formas"],
    grade: "3° de primaria",
    pages: 48,
    format: "Digital (PDF interactivo)",
    idioma: "Inglés - Español",
    description:
      "Aprende los colores y las formas geométricas con actividades para pintar, recortar y clasificar.",
    learn: [
      "Colores primarios y secundarios",
      "Formas geométricas",
      "Descripciones simples",
      "Juegos de clasificación",
      "Ilustraciones a todo color",
    ],
    vocab: [
      { word: "Red", emoji: "🔴" },
      { word: "Blue", emoji: "🔵" },
      { word: "Yellow", emoji: "🟡" },
      { word: "Green", emoji: "🟢" },
      { word: "Circle", emoji: "⚪" },
      { word: "Square", emoji: "◼️" },
      { word: "Triangle", emoji: "🔺" },
      { word: "Star", emoji: "⭐" },
    ],
  },
  {
    id: "numbers-everywhere",
    title: "Numbers Everywhere",
    category: "numeros",
    unit: "Unidad 1 - 4",
    art: "numbers",
    topics: ["Números", "Conteo"],
    grade: "3° de primaria",
    pages: 50,
    format: "Digital (PDF interactivo)",
    idioma: "Inglés - Español",
    description: "Cuenta, suma y juega mientras aprendes los números en inglés del 1 al 100.",
    learn: [
      "Números del 1 al 20",
      "Conteo y secuencias",
      "Preguntas con how many",
      "Juegos numéricos",
      "Ilustraciones a todo color",
    ],
    vocab: [
      { word: "One", emoji: "1️⃣" },
      { word: "Two", emoji: "2️⃣" },
      { word: "Three", emoji: "3️⃣" },
      { word: "Four", emoji: "4️⃣" },
      { word: "Five", emoji: "5️⃣" },
      { word: "Six", emoji: "6️⃣" },
      { word: "Seven", emoji: "7️⃣" },
      { word: "Eight", emoji: "8️⃣" },
    ],
  },
  {
    id: "my-amazing-body",
    title: "My Amazing Body",
    category: "cuerpo",
    unit: "Unidad 1 - 4",
    art: "body",
    topics: ["Cuerpo humano", "Salud"],
    grade: "3° de primaria",
    pages: 52,
    format: "Digital (PDF interactivo)",
    idioma: "Inglés - Español",
    description: "Conoce las partes del cuerpo humano y aprende a hablar sobre cómo te sientes en inglés.",
    learn: [
      "Partes del cuerpo",
      "Sentidos",
      "Frases sobre salud (I feel...)",
      "Actividades interactivas",
      "Ilustraciones a todo color",
    ],
    vocab: [
      { word: "Head", emoji: "🧠" },
      { word: "Hand", emoji: "✋" },
      { word: "Foot", emoji: "🦶" },
      { word: "Eye", emoji: "👀" },
      { word: "Ear", emoji: "👂" },
      { word: "Nose", emoji: "👃" },
      { word: "Mouth", emoji: "👄" },
      { word: "Arm", emoji: "💪" },
    ],
  },
  {
    id: "places-i-know",
    title: "Places I Know",
    category: "lugares",
    unit: "Unidad 1 - 5",
    art: "places",
    topics: ["Lugares", "Ciudad"],
    grade: "3° de primaria",
    pages: 56,
    format: "Digital (PDF interactivo)",
    idioma: "Inglés - Español",
    description: "Recorre lugares de tu comunidad y aprende a dar direcciones sencillas en inglés.",
    learn: [
      "Lugares de la comunidad",
      "Direcciones simples",
      "Preposiciones de lugar",
      "Juegos de ubicación",
      "Ilustraciones a todo color",
    ],
    vocab: [
      { word: "Park", emoji: "🏞️" },
      { word: "School", emoji: "🏫" },
      { word: "Hospital", emoji: "🏥" },
      { word: "Store", emoji: "🏬" },
      { word: "House", emoji: "🏠" },
      { word: "Beach", emoji: "🏖️" },
      { word: "Zoo", emoji: "🐾" },
      { word: "Library", emoji: "📚" },
    ],
  },
  {
    id: "special-celebrations",
    title: "Special Celebrations",
    category: "celebraciones",
    unit: "Unidad 1 - 4",
    art: "party",
    topics: ["Celebraciones", "Cultura"],
    grade: "3° de primaria",
    pages: 46,
    format: "Digital (PDF interactivo)",
    idioma: "Inglés - Español",
    description: "Celebra fechas especiales del año mientras aprendes vocabulario cultural en inglés.",
    learn: [
      "Fechas y celebraciones",
      "Vocabulario cultural",
      "Frases de felicitación",
      "Manualidades y juegos",
      "Ilustraciones a todo color",
    ],
    vocab: [
      { word: "Birthday", emoji: "🎂" },
      { word: "Christmas", emoji: "🎄" },
      { word: "Halloween", emoji: "🎃" },
      { word: "New Year", emoji: "🎆" },
      { word: "Easter", emoji: "🐣" },
      { word: "Party", emoji: "🎉" },
      { word: "Gift", emoji: "🎁" },
      { word: "Balloon", emoji: "🎈" },
    ],
  },
];

export const RESOURCES = [
  { id: "r1", type: "video", title: "The Alphabet Song", duration: "2:50", emoji: "🔤", speak: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z" },
  { id: "r2", type: "video", title: "Numbers 1 to 100", duration: "3:10", emoji: "🔢", speak: "One, two, three, four, five, six, seven, eight, nine, ten" },
  { id: "r3", type: "video", title: "Colors for Kids", duration: "2:40", emoji: "🌈", speak: "Red, orange, yellow, green, blue, purple, pink, black, white" },
  { id: "r4", type: "video", title: "Animals Song", duration: "2:50", emoji: "🦁", speak: "Lion, elephant, cat, dog, bird, fish, monkey, rabbit" },
  { id: "r5", type: "video", title: "Animals Song 2", duration: "3:20", emoji: "🐘", speak: "Tiger, bear, zebra, giraffe, horse, sheep, duck, frog" },
  { id: "r6", type: "imprimible", title: "Flashcards para imprimir", emoji: "🃏" },
  { id: "r7", type: "imprimible", title: "Posters educativos", emoji: "🖼️" },
  { id: "r8", type: "imprimible", title: "Hojas de trabajo (PDF)", emoji: "📝" },
  { id: "r9", type: "juego", title: "Juegos en línea", emoji: "🎮" },
];

export function getBookById(id) {
  return BOOKS.find((b) => b.id === id);
}

export function getAllVocab() {
  const all = [];
  BOOKS.forEach((book) => {
    book.vocab.forEach((v) => all.push({ ...v, book: book.title }));
  });
  return all;
}
