import { WORKBOOK_PAGES } from './workbooks';

// Datos centrales del sitio EnglishKids: libros, categorías y vocabulario.
// "art" selecciona la ilustración SVG de portada (components/illustrations/BookCoverArt.js).
// "emoji" se usa para tarjetas pequeñas de vocabulario (flashcards, quiz, vista previa).

export const CATEGORIES = [
  { id: "todos", label: "Todos" },
  { id: "escuela", label: "Escuela" },
  { id: "familia", label: "Familia" },
  { id: "animales", label: "Animales" },
  { id: "comida", label: "Comida" },
  { id: "naturaleza", label: "Naturaleza" },
  { id: "colores", label: "Colores y formas" },
  { id: "numeros", label: "Números" },
  { id: "cuerpo", label: "Cuerpo humano" },
  { id: "lugares", label: "Lugares" },
  { id: "celebraciones", label: "Celebraciones" },
];

export const CATEGORY_ICONS = {
  todos: "all",
  escuela: "home",
  familia: "users",
  animales: "paw",
  comida: "utensils",
  naturaleza: "leaf",
  colores: "palette",
  numeros: "hash",
  cuerpo: "person",
  lugares: "pin",
  celebraciones: "gift",
};

export const CATEGORY_COLORS = {
  escuela: "blue",
  familia: "pink",
  animales: "green",
  comida: "orange",
  naturaleza: "teal",
  colores: "purple",
  numeros: "blue",
  cuerpo: "pink",
  lugares: "teal",
  celebraciones: "orange",
};

export const TAG_CLASSES = {
  blue: "bg-brand-blue",
  pink: "bg-brand-pink",
  green: "bg-brand-green",
  orange: "bg-brand-orange",
  teal: "bg-brand-teal",
  purple: "bg-brand-purple",
};

export const COVER_GRADIENTS = {
  escuela: "from-[#d9e8ff] to-[#b7d1ff]",
  familia: "from-[#ffdde6] to-[#ffc2d1]",
  animales: "from-[#d8f5e9] to-[#b3ebd0]",
  comida: "from-[#ffe6cf] to-[#ffd1a3]",
  naturaleza: "from-[#d3f3ee] to-[#a8e6da]",
  colores: "from-[#ecdcff] to-[#d7bfff]",
  numeros: "from-[#d9e8ff] to-[#b7d1ff]",
  cuerpo: "from-[#ffdde6] to-[#ffc2d1]",
  lugares: "from-[#d3f3ee] to-[#a8e6da]",
  celebraciones: "from-[#ffe6cf] to-[#ffd1a3]",
};

export const BOOK_PALETTES = {
  "my-world-in-english": { bg: "#e0f2fe", ink: "#0369a1", catBg: "#dbeafe", catColor: "#1d4ed8" },
  "animals-around-us": { bg: "#dcfce7", ink: "#15803d", catBg: "#dcfce7", catColor: "#15803d" },
  "at-school": { bg: "#ffedd5", ink: "#c2410c", catBg: "#ffedd5", catColor: "#c2410c" },
  "my-family": { bg: "#fef9c3", ink: "#a16207", catBg: "#fef9c3", catColor: "#a16207" },
  "food-and-fun": { bg: "#ffe4e6", ink: "#be123c", catBg: "#ffe4e6", catColor: "#be123c" },
  "nature-around-us": { bg: "#ccfbf1", ink: "#0f766e", catBg: "#ccfbf1", catColor: "#0f766e" },
  "colors-and-shapes": { bg: "#f3e8ff", ink: "#7e22ce", catBg: "#f3e8ff", catColor: "#7e22ce" },
  "numbers-everywhere": { bg: "#e0e7ff", ink: "#4338ca", catBg: "#e0e7ff", catColor: "#4338ca" },
  "my-amazing-body": { bg: "#ffe4e6", ink: "#e11d48", catBg: "#ffe4e6", catColor: "#e11d48" },
  "places-i-know": { bg: "#dbeafe", ink: "#1d4ed8", catBg: "#dbeafe", catColor: "#1d4ed8" },
  "special-celebrations": { bg: "#ffedd5", ink: "#c2410c", catBg: "#ffedd5", catColor: "#c2410c" },
};

export function getBookPalette(id) {
  return BOOK_PALETTES[id] || { bg: "#f1f5f9", ink: "#073471", catBg: "#f1f5f9", catColor: "#073471" };
}

export const UPLOADED_COVERS = new Set([
  "my-world-in-english",
  "animals-around-us",
  "at-school",
  "my-family",
  "food-and-fun",
  "nature-around-us",
  "colors-and-shapes",
  "numbers-everywhere",
  "my-amazing-body",
  "places-i-know",
  "special-celebrations",
]);

export const BOOKS = [
  {
    id: "my-world-in-english",
    title: "My World in English",
    category: "escuela",
    unit: "Unidad 1 - 6",
    art: "world",
    topics: ["Vocabulario", "Saludos", "Presentaciones"],
    grade: "3° de primaria",
    pages: WORKBOOK_PAGES.length,
    format: "Digital (PDF para imprimir)",
    idioma: "Inglés - Español",
    rating: 4.8,
    reviews: 120,
    description:
      "Un libro interactivo lleno de historias cotidianas, diálogos ilustrados y dinámicas prácticas para que los niños se comuniquen en inglés con naturalidad. Aprende saludos, fórmulas de cortesía, presentaciones personales y vocabulario básico con ejercicios dinámicos diseñados especialmente para 3° de primaria.",
    learn: [
      "Saludos y presentaciones",
      "Vocabulario básico",
      "Conversaciones sencillas",
      "Actividades interactivas",
      "Ilustraciones a todo color",
    ],
    vocab: [
      { word: "Hello", emoji: "👋" },
      { word: "Hi", emoji: "🙋" },
      { word: "Good morning", emoji: "🌅" },
      { word: "Good afternoon", emoji: "🌤️" },
      { word: "Good night", emoji: "🌙" },
      { word: "Bye", emoji: "👋" },
      { word: "See you", emoji: "😊" },
    ],
  },
  {
    id: "animals-around-us",
    title: "Animals Around Us",
    category: "animales",
    unit: "Unidad 1 - 6",
    art: "animals",
    topics: ["Animales", "Naturaleza"],
    grade: "3° de primaria",
    pages: WORKBOOK_PAGES.length,
    format: "Digital (PDF para imprimir)",
    idioma: "Inglés - Español",
    rating: 4.7,
    reviews: 98,
    description:
      "Descubre la fascinante fauna del planeta mientras aprendes sus nombres en inglés con historias guiadas, juegos de memoria y actividades para colorear. Conoce sus hábitats naturales, sonidos característicos y frases descriptivas simples con pronunciación clara y divertida.",
    learn: [
      "Nombres de animales",
      "Sonidos y hábitats",
      "Frases descriptivas simples",
      "Juegos de memoria",
      "Ilustraciones a todo color",
    ],
    vocab: [
      { word: "Lion", emoji: "🦁" },
      { word: "Elephant", emoji: "🐘" },
      { word: "Cat", emoji: "🐱" },
      { word: "Dog", emoji: "🐶" },
      { word: "Bird", emoji: "🐦" },
      { word: "Fish", emoji: "🐟" },
      { word: "Monkey", emoji: "🐒" },
      { word: "Rabbit", emoji: "🐰" },
    ],
  },
  {
    id: "at-school",
    title: "At School",
    category: "escuela",
    unit: "Unidad 1 - 6",
    art: "school",
    topics: ["Escuela", "Objetos"],
    grade: "3° de primaria",
    pages: WORKBOOK_PAGES.length,
    format: "Digital (PDF para imprimir)",
    idioma: "Inglés - Español",
    rating: 4.6,
    reviews: 87,
    description:
      "Aprende el vocabulario esencial del salón de clases: útiles escolares (pencil, notebook, ruler), materias divertidas, profesores y rutinas diarias en la escuela. Descubre cómo pedir materiales prestados, seguir instrucciones del docente y responder preguntas cotidianas en inglés con total seguridad y entusiasmo.",
    learn: [
      "Útiles escolares",
      "Personas en la escuela",
      "Rutinas y horarios",
      "Preguntas y respuestas simples",
      "Ilustraciones a todo color",
    ],
    vocab: [
      { word: "Book", emoji: "📖" },
      { word: "Pencil", emoji: "✏️" },
      { word: "Backpack", emoji: "🎒" },
      { word: "Teacher", emoji: "🧑‍🏫" },
      { word: "Classroom", emoji: "🏫" },
      { word: "Chair", emoji: "🪑" },
      { word: "Desk", emoji: "🪵" },
      { word: "Ruler", emoji: "📏" },
    ],
  },
  {
    id: "my-family",
    title: "My Family",
    category: "familia",
    unit: "Unidad 1 - 6",
    art: "family",
    topics: ["Familia", "Personas"],
    grade: "3° de primaria",
    pages: WORKBOOK_PAGES.length,
    format: "Digital (PDF para imprimir)",
    idioma: "Inglés - Español",
    rating: 4.9,
    reviews: 143,
    description:
      "Conoce a todos los miembros de la familia y aprende a describir a las personas que más quieres en inglés. Practica el uso de pronombres posesivos, la creación de tu propio árbol genealógico y frases cariñosas a través de lecturas interactivas e ilustraciones llenas de color.",
    learn: [
      "Miembros de la familia",
      "Descripciones simples",
      "Posesivos básicos (my, your)",
      "Actividades interactivas",
      "Ilustraciones a todo color",
    ],
    vocab: [
      { word: "Mother", emoji: "👩" },
      { word: "Father", emoji: "👨" },
      { word: "Sister", emoji: "👧" },
      { word: "Brother", emoji: "👦" },
      { word: "Grandmother", emoji: "👵" },
      { word: "Grandfather", emoji: "👴" },
      { word: "Baby", emoji: "👶" },
      { word: "Family", emoji: "👨‍👩‍👧‍👦" },
    ],
  },
  {
    id: "food-and-fun",
    title: "Food and Fun",
    category: "comida",
    unit: "Unidad 1 - 6",
    art: "food",
    topics: ["Comida", "Vocabulario"],
    grade: "3° de primaria",
    pages: WORKBOOK_PAGES.length,
    format: "Digital (PDF para imprimir)",
    idioma: "Inglés - Español",
    rating: 4.5,
    reviews: 76,
    description:
      "Un recorrido delicioso por el vocabulario de la comida, las frutas nutritivas, bebidas y platillos favoritos. Aprende a expresar tus gustos y preferencias con soltura (I like / I don't like), adivinanzas de cocina, diálogos en el restaurante y recetas ilustradas paso a paso.",
    learn: [
      "Nombres de alimentos",
      "Gustos y preferencias (I like / I don't like)",
      "Comidas del día",
      "Juegos de vocabulario",
      "Ilustraciones a todo color",
    ],
    vocab: [
      { word: "Pizza", emoji: "🍕" },
      { word: "Apple", emoji: "🍎" },
      { word: "Milk", emoji: "🥛" },
      { word: "Bread", emoji: "🍞" },
      { word: "Juice", emoji: "🧃" },
      { word: "Cake", emoji: "🍰" },
      { word: "Rice", emoji: "🍚" },
      { word: "Egg", emoji: "🥚" },
    ],
  },
  {
    id: "nature-around-us",
    title: "Nature Around Us",
    category: "naturaleza",
    unit: "Unidad 1 - 6",
    art: "nature",
    topics: ["Naturaleza", "Plantas"],
    grade: "3° de primaria",
    pages: WORKBOOK_PAGES.length,
    format: "Digital (PDF para imprimir)",
    idioma: "Inglés - Español",
    rating: 4.7,
    reviews: 91,
    description:
      "Explora el fascinante mundo natural: plantas, flores, estaciones del año, el clima y los paisajes mientras amplías tu vocabulario en inglés. Ideal para conectar el aprendizaje con el entorno que te rodea y desarrollar habilidades de comprensión descriptiva y observación.",
    learn: [
      "Elementos de la naturaleza",
      "El clima",
      "Frases descriptivas",
      "Actividades al aire libre",
      "Ilustraciones a todo color",
    ],
    vocab: [
      { word: "Tree", emoji: "🌳" },
      { word: "Flower", emoji: "🌸" },
      { word: "Sun", emoji: "☀️" },
      { word: "Moon", emoji: "🌙" },
      { word: "River", emoji: "🏞️" },
      { word: "Mountain", emoji: "⛰️" },
      { word: "Cloud", emoji: "☁️" },
      { word: "Rainbow", emoji: "🌈" },
    ],
  },
  {
    id: "colors-and-shapes",
    title: "Colors and Shapes",
    category: "colores",
    unit: "Unidad 1 - 4",
    art: "colors",
    topics: ["Colores", "Formas"],
    grade: "3° de primaria",
    pages: WORKBOOK_PAGES.length,
    format: "Digital (PDF para imprimir)",
    idioma: "Inglés - Español",
    rating: 4.4,
    reviews: 54,
    description:
      "Aprende a identificar y combinar los colores primarios y secundarios junto con las figuras geométricas de la vida diaria. Desarrolla el pensamiento lógico y espacial mediante divertidos retos de clasificación, patrones visuales y creativos ejercicios para dibujar y colorear.",
    learn: [
      "Colores primarios y secundarios",
      "Formas geométricas",
      "Descripciones simples",
      "Juegos de clasificación",
      "Ilustraciones a todo color",
    ],
    vocab: [
      { word: "Red", emoji: "🔴" },
      { word: "Blue", emoji: "🔵" },
      { word: "Yellow", emoji: "🟡" },
      { word: "Green", emoji: "🟢" },
      { word: "Circle", emoji: "⚪" },
      { word: "Square", emoji: "◼️" },
      { word: "Triangle", emoji: "🔺" },
      { word: "Star", emoji: "⭐" },
    ],
  },
  {
    id: "numbers-everywhere",
    title: "Numbers Everywhere",
    category: "numeros",
    unit: "Unidad 1 - 4",
    art: "numbers",
    topics: ["Números", "Conteo"],
    grade: "3° de primaria",
    pages: WORKBOOK_PAGES.length,
    format: "Digital (PDF para imprimir)",
    idioma: "Inglés - Español",
    rating: 4.3,
    reviews: 47,
    description:
      "Cuenta, suma y juega mientras aprendes los números en inglés del 1 al 100. Incluye dinámicas de conteo rápido, secuencias numéricas divertidas y preguntas cotidianas de cantidad diseñadas para que las matemáticas en inglés sean intuitivas y entretenidas.",
    learn: [
      "Números del 1 al 20",
      "Conteo y secuencias",
      "Preguntas con how many",
      "Juegos numéricos",
      "Ilustraciones a todo color",
    ],
    vocab: [
      { word: "One", emoji: "1️⃣" },
      { word: "Two", emoji: "2️⃣" },
      { word: "Three", emoji: "3️⃣" },
      { word: "Four", emoji: "4️⃣" },
      { word: "Five", emoji: "5️⃣" },
      { word: "Six", emoji: "6️⃣" },
      { word: "Seven", emoji: "7️⃣" },
      { word: "Eight", emoji: "8️⃣" },
    ],
  },
  {
    id: "my-amazing-body",
    title: "My Amazing Body",
    category: "cuerpo",
    unit: "Unidad 1 - 4",
    art: "body",
    topics: ["Cuerpo humano", "Salud"],
    grade: "3° de primaria",
    pages: WORKBOOK_PAGES.length,
    format: "Digital (PDF para imprimir)",
    idioma: "Inglés - Español",
    rating: 4.6,
    reviews: 62,
    description:
      "Conoce las partes del cuerpo humano, los cinco sentidos y aprende a comunicar cómo te sientes, tus emociones o qué necesitas en inglés. Acompañado de alegres canciones, rimas de movimiento y ejercicios prácticos que hacen de cada lección una experiencia activa.",
    learn: [
      "Partes del cuerpo",
      "Sentidos",
      "Frases sobre salud (I feel...)",
      "Actividades interactivas",
      "Ilustraciones a todo color",
    ],
    vocab: [
      { word: "Head", emoji: "🧠" },
      { word: "Hand", emoji: "✋" },
      { word: "Foot", emoji: "🦶" },
      { word: "Eye", emoji: "👀" },
      { word: "Ear", emoji: "👂" },
      { word: "Nose", emoji: "👃" },
      { word: "Mouth", emoji: "👄" },
      { word: "Arm", emoji: "💪" },
    ],
  },
  {
    id: "places-i-know",
    title: "Places I Know",
    category: "lugares",
    unit: "Unidad 1 - 5",
    art: "places",
    topics: ["Lugares", "Ciudad"],
    grade: "3° de primaria",
    pages: WORKBOOK_PAGES.length,
    format: "Digital (PDF para imprimir)",
    idioma: "Inglés - Español",
    rating: 4.5,
    reviews: 58,
    description:
      "Recorre los lugares más importantes de tu comunidad: parques, bibliotecas, tiendas, hospitales y escuelas mientras aprendes a dar indicaciones sencillas y usar preposiciones de lugar con mapas interactivos y divertidos juegos de exploración urbana.",
    learn: [
      "Lugares de la comunidad",
      "Direcciones simples",
      "Preposiciones de lugar",
      "Juegos de ubicación",
      "Ilustraciones a todo color",
    ],
    vocab: [
      { word: "Park", emoji: "🏞️" },
      { word: "School", emoji: "🏫" },
      { word: "Hospital", emoji: "🏥" },
      { word: "Store", emoji: "🏬" },
      { word: "House", emoji: "🏠" },
      { word: "Beach", emoji: "🏖️" },
      { word: "Zoo", emoji: "🐾" },
      { word: "Library", emoji: "📚" },
    ],
  },
  {
    id: "special-celebrations",
    title: "Special Celebrations",
    category: "celebraciones",
    unit: "Unidad 1 - 4",
    art: "party",
    topics: ["Celebraciones", "Cultura"],
    grade: "3° de primaria",
    pages: WORKBOOK_PAGES.length,
    format: "Digital (PDF para imprimir)",
    idioma: "Inglés - Español",
    rating: 4.8,
    reviews: 70,
    description:
      "Celebra los momentos más felices del año: cumpleaños, festividades y tradiciones mientras descubres vocabulario cultural en inglés. Aprende a redactar mensajes de felicitación, participar en juegos temáticos y conocer cómo se festeja en distintas partes del mundo.",
    learn: [
      "Fechas y celebraciones",
      "Vocabulario cultural",
      "Frases de felicitación",
      "Manualidades y juegos",
      "Ilustraciones a todo color",
    ],
    vocab: [
      { word: "Birthday", emoji: "🎂" },
      { word: "Christmas", emoji: "🎄" },
      { word: "Halloween", emoji: "🎃" },
      { word: "New Year", emoji: "🎆" },
      { word: "Easter", emoji: "🐣" },
      { word: "Party", emoji: "🎉" },
      { word: "Gift", emoji: "🎁" },
      { word: "Balloon", emoji: "🎈" },
    ],
  },
];

export const RESOURCES = [
  { id: "r1", type: "audio", title: "The Alphabet Song", emoji: "🔤", image: "/resources-images/r1-alphabet-song.png", imageAspect: "1672 / 941", speak: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z" },
  { id: "r2", type: "audio", title: "Numbers 1 to 100", emoji: "🔢", image: "/resources-images/r2-numbers-1-100.png", imageAspect: "1672 / 941", speak: "One, two, three, four, five, six, seven, eight, nine, ten" },
  { id: "r3", type: "audio", title: "Colors for Kids", emoji: "🌈", image: "/resources-images/r3-colors-for-kids.png", imageAspect: "1672 / 941", speak: "Red, orange, yellow, green, blue, purple, pink, black, white" },
  { id: "r4", type: "audio", title: "Animals Song", emoji: "🦁", image: "/resources-images/r4-animals-song.png", imageAspect: "1672 / 941", speak: "Lion, elephant, cat, dog, bird, fish, monkey, rabbit" },
  { id: "r5", type: "audio", title: "Animals Song 2", emoji: "🐘", image: "/resources-images/r5-animals-song-2.png", imageAspect: "1672 / 941", speak: "Tiger, bear, zebra, giraffe, horse, sheep, duck, frog" },
  { id: "r6", type: "imprimible", title: "Flashcards para imprimir", emoji: "🃏", image: "/resources-images/r6-flashcards.png", imageAspect: "1672 / 941" },
  { id: "r7", type: "imprimible", title: "Posters educativos", emoji: "🖼️", image: "/resources-images/r7-posters.png", imageAspect: "1671 / 941" },
  { id: "r8", type: "imprimible", title: "Hojas de trabajo (PDF)", emoji: "📝", image: "/resources-images/r8-worksheets-v2.png", imageAspect: "1536 / 1024" },
  { id: "r9", type: "juego", title: "Juegos en línea", emoji: "🎮", image: "/resources-images/r9-juegos.png", imageAspect: "1672 / 941" },
];

export function getBookById(id) {
  return BOOKS.find((b) => b.id === id);
}

export function getAllVocab() {
  const all = [];
  BOOKS.forEach((book) => {
    book.vocab.forEach((v) => all.push({ ...v, book: book.title }));
  });
  return all;
}
